<?php

/****************************************
* Theme Options Pages and content elements
****************************************/


# Fetching one time actual categories of posts
$categories_obj = get_categories( array('type'=>'post') );
foreach ($categories_obj as $cobj) {
    $categories[$cobj->cat_ID] = $cobj->name;
}


# Defining theme options pages with their elements
$vz_theme_options_pages = array(

    /*********************
    * General 
    *********************/
    'vz_options_arch' => array(
        __('Theme Architecture', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Architecture', 'vz_terms') => array( 
            'type' => 'architecture'),  ),

    'vz_options_home' => array(
        __('Homepage slider', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Use Slider', 'vz_terms') => array( 
            'type' => 'checkbox', 
            'name' => 'slider_disabled',
            'default' => 'enabled',
            'description' => __('Using slider would make your site more interactive and modern.', 'vz_terms')),
        __('Show captions', 'vz_terms') => array( 
            'type' => 'checkbox', 
            'name' => 'captions_disabled',
            'default' => 'enabled',
            'description' => __('Showing captions would help visitors to understand the post.', 'vz_terms')),
        __('  Posts category', 'vz_terms') => array( 
            'type' => 'selectbox',
            'name' => 'slider_cat',
            'options' => $categories,
            'use_key' => TRUE,
            'size'    => 'half',
            'none' => __('Any category', 'vz_terms') ),
        __('  Number of posts', 'vz_terms') => array( 
            'type' => 'selectbox',
            'name' => 'slider_num',
            'options' => array('4','5','6','7','8','9','10'),
            'size'    => 'half',
            'none' => 3 ),
        __('Next slide after X seconds', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'next_slide',
            'default' => '7',
            'size'    => 'half'),
        __('Slider height px, default 330px', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'slider_height',
            'default' => '330',
            'size' => 'half'),
        __('Featured articles', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Show featured articles', 'vz_terms') => array( 
            'type' => 'checkbox', 
            'name' => 'featuredarticles_disabled',
            'default' => 'enabled',
            'description' => __('Showing featured articles may motivate users to post.', 'vz_terms') ),  
        __('Posts category', 'vz_terms') => array( 
            'type' => 'selectbox',
            'name' => 'featured_cat',
            'options' => $categories,
            'use_key' => TRUE,
            'size'    => 'half',
            'none' => __('Any category', 'vz_terms') ),
        __('Number of posts', 'vz_terms') => array( 
            'type' => 'selectbox',
            'name' => 'featured_num',
            'options' => array('3','4','5'),
            'size'    => 'half',
            'none' => 2 ),
        __('News block', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Show news block', 'vz_terms') => array( 
            'type' => 'checkbox', 
            'name' => 'newsblock_disabled',
            'default' => 'enabled',
            'description' => __('Showing news block may help visitors with news orientation.', 'vz_terms') ),  
        __(' Posts category', 'vz_terms') => array( 
            'type' => 'selectbox',
            'name' => 'newsblock_cat',
            'options' => $categories,
            'use_key' => TRUE,
            'size'    => 'half',
            'none' => __('Any category', 'vz_terms') ),
        __(' Number of posts', 'vz_terms') => array( 
            'type' => 'selectbox',
            'name' => 'newsblock_num',
            'options' => array('5','6','7','8'),
            'size'    => 'half',
            'none' => 4 ),
        __('Events block', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Show events block', 'vz_terms') => array( 
            'type' => 'checkbox', 
            'name' => 'eventsblock_disabled',
            'default' => 'enabled',
            'description' => __('Showing events block may help visitors with staying up to date with events.', 'vz_terms') ),  
        __(' Number of events', 'vz_terms') => array( 
            'type' => 'selectbox',
            'name' => 'eventsblock_num',
            'options' => array('5','6','7','8'),
            'none' => 4 ),  ),

    'vz_options_btemp' => array(
        __('Blog, category', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Number of sticky posts', 'vz_terms') => array( 
            'type' => 'selectbox',
            'name' => 'num',
            'options' => array('6','7','8','9','10'),
            'none' => 5,
            'default' => get_option('vz_options_btemp_sticky',5) ),
        __('Blog template', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Number of posts', 'vz_terms') => array( 
            'type' => 'selectbox',
            'name' => 'num',
            'options' => array('6','7','8','9','10'),
            'none' => 5,
            'default' => get_option('vz_options_btemp_num',5) ),
        __('Single Blog post', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Show author info', 'vz_terms') => array( 
            'type' => 'checkbox', 
            'name' => 'author_disabled',
            'default' => 'enabled',
            'description' => __('Showing author info could inspire users to blog more.', 'vz_terms') ),  
        __('Show categories', 'vz_terms') => array( 
            'type' => 'checkbox', 
            'name' => 'cat_disabled',
            'default' => 'enabled',
            'description' => __('Showing categories could teach visitors where to find articles.', 'vz_terms') ), 
        __('Show tags', 'vz_terms') => array( 
            'type' => 'checkbox', 
            'name' => 'tag_disabled',
            'default' => 'enabled',
            'description' => __('Showing tags could help visitors learn how to search.', 'vz_terms') ), ),

    'vz_options_ct' => array(
        __('Contact template details', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Show map', 'vz_terms') => array( 
            'type' => 'checkbox', 
            'name' => 'map_disabled',
            'default' => 'enabled',
            'description' => __('Showing map could help visitors where to find your office.', 'vz_terms') ), 
        __('Latitude,Longtitude or iframe code', 'vz_terms') => array( 
            'type' => 'textarea',
            'name' => 'lat_lon'),
        __('Sidebar title', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'side_title',
            'default' => 'Information'),
        __('Phone label', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'phone_label',
            'default' => 'Phone'),
        __('Phone Content', 'vz_terms') => array( 
            'type' => 'textarea',
            'height' => 60,
            'name' => 'phone'),
        __('Address label', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'address_label',
            'default' => 'Office Address'),
        __('Address Content', 'vz_terms') => array( 
            'type' => 'textarea',
            'height' => 60,
            'name' => 'address'),
        __('Email label', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'email_label',
            'default' => 'Email'),
        __('Email Content', 'vz_terms') => array( 
            'type' => 'textarea',
            'height' => 60,
            'name' => 'email'),
        __('Staff label', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'staff_label',
            'default' => 'Public relations'),
        __('Staff Content', 'vz_terms') => array( 
            'type' => 'textarea',
            'height' => 60,
            'name' => 'staff'), ),

    'vz_options_look' => array(
        __('Logo', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Upload or link your logo (90x90px)', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'logo',
            'class'=> 'upload_field',
            'file' => TRUE,
            'init' => 'url'),
        __('Logo Ad code (468x60px)', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('(html/javascript)', 'vz_terms') => array( 
            'type' => 'textarea',
            'name' => 'ad_code'),
        __('Favicon', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Use favicon', 'vz_terms') => array( 
            'type' => 'checkbox', 
            'name' => 'fav_enabled',
            'description' => __('Favicon helps your website branding.', 'vz_terms') ),
        __('FAVICON (16x16px .ico)', 'vz_terms') => array( 
            'type' => 'input', 
            'name' => 'favicon',
            'class'=> 'upload_field',
            'file' => TRUE,
            'init' => 'url'),
        __('Site body', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Background image', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'bg_img',
            'class'=> 'upload_field',
            'file' => TRUE,
            'init' => 'url'),
        __('Background image repeat', 'vz_terms') => array( 
            'type' => 'selectbox',
            'name' => 'bg_img_repeat',
            'options'=> array('repeat','repeat-x','repeat-y')),
        __('Background color', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'name' => 'bg_color',
            'size' => 'short',
            'init' => 'hex'), ),

    'vz_options_social' => array(
        __('Sharing', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Facebook ', 'vz_terms') => array( 
            'type' => 'checkbox', 
            'name' => 'fb_disabled',
            'default' => 'enabled',
            'description' => __('Let users share posts on Facebook.', 'vz_terms') ),
        __('Twitter ', 'vz_terms') => array( 
            'type' => 'checkbox', 
            'name' => 'tw_disabled',
            'default' => 'enabled',
            'description' => __('Let users share posts on Twitter.', 'vz_terms') ),
        __('Google', 'vz_terms') => array( 
            'type' => 'checkbox', 
            'name' => 'gg_disabled',
            'default' => 'enabled',
            'description' => __('Let users share posts on Google.', 'vz_terms') ),
        __('LinkedIn', 'vz_terms') => array( 
            'type' => 'checkbox', 
            'name' => 'li_disabled',
            'default' => 'enabled',
            'description' => __('Let users share posts on LinkedIn.', 'vz_terms') ),
        __('Feeding (check checkbox to show icon on site)', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('RSS', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'rss',
            'cb_show' => 'yes',
            'init' => 'url'),
        __('Networking (check checkbox to show icon on site)', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Facebook', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'fb',
            'cb_show' => 'yes',
            'init' => 'url'),
        __('Twitter', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'tw',
            'cb_show' => 'yes',
            'init' => 'url'),
        __('Google+', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'gplus',
            'cb_show' => 'yes',
            'init' => 'url'),
        __(' LinkedIn', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'lin',
            'cb_show' => 'yes',
            'init' => 'url'),
        __('Skype', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'skype',
            'cb_show' => 'yes',
            'init' => 'url'),
        __('Youtube', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'yt',
            'cb_show' => 'yes',
            'init' => 'url'),
        __('Vimeo', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'vimeo',
            'cb_show' => 'yes',
            'init' => 'url'),
        __('Instagram', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'igram',
            'cb_show' => 'yes',
            'init' => 'url'),
        __('Pinterest', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'pin',
            'cb_show' => 'yes',
            'init' => 'url'),
        __('Dribbble', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'dribbble',
            'cb_show' => 'yes',
            'init' => 'url'),
        __('Xing', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'xing',
            'cb_show' => 'yes',
            'init' => 'url'),
        __('Tumblr', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'tumblr',
            'cb_show' => 'yes',
            'init' => 'url'), ),

    'vz_options_lang_links' => array(
        __('Language links', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Show language links', 'vz_terms') => array( 
            'type' => 'checkbox', 
            'name' => 'enabled',
            'description' => __('Near social icons show language links.', 'vz_terms') ), 
        __('Language Initial and Link', 'vz_terms') => array( 
            'type' => 'doubleinput',
            'name' => 'firstlang'),
        __('Language Initial and Link ', 'vz_terms') => array( 
            'type' => 'doubleinput',
            'name' => 'secondlang',
            'init' => ''),
        __(' Language Initial and Link ', 'vz_terms') => array( 
            'type' => 'doubleinput',
            'name' => 'thirdlang'),
        __('  Language Initial and Link ', 'vz_terms') => array( 
            'type' => 'doubleinput',
            'name' => 'fourthlang'), ),

    'vz_options_slugs' => array(
        __('Custom posts slugs', 'vz_terms') => array( 
            'type' => 'heading' ),
        'Single Event slug (Example: http://'.$_SERVER["SERVER_NAME"].'/event )' => array( 
            'type' => 'input',
            'name' => 'events',
            'default' => 'event'),
        'Single Course slug (Example: http://'.$_SERVER["SERVER_NAME"].'/course )' => array( 
            'type' => 'input',
            'name' => 'courses',
            'default' => 'course'),
        'Single Gallery slug (Example: http://'.$_SERVER["SERVER_NAME"].'/gal )' => array( 
            'type' => 'input',
            'name' => 'gal',
            'default' => 'gal'),
        'Single Staff slug (Example: http://'.$_SERVER["SERVER_NAME"].'/staff )' => array( 
            'type' => 'input',
            'name' => 'staff',
            'default' => 'staff'),
        'Single Book slug (Example: http://'.$_SERVER["SERVER_NAME"].'/book )' => array( 
            'type' => 'input',
            'name' => 'book',
            'default' => 'book'), ),

    'vz_options_google_analytics' => array(
        __('Tracking', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Enable google analytics', 'vz_terms') => array( 
            'type' => 'checkbox', 
            'name' => 'enabled',
            'description' => __('Track your website visitors behaviours in a professional way.', 'vz_terms') ),
        __('Analytics Code', 'vz_terms') => array( 
            'type' => 'textarea',
            'name' => 'code'), ),



    /*********************
    * Text editing 
    *********************/
    'vz_text_header' => array(
        __('Header Texting', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Show header titles', 'vz_terms') => array( 
            'type' => 'checkbox', 
            'name' => 'htext_disabled',
            'default' => 'enabled',
            'description' => __('Showing header titles is optional.', 'vz_terms')),
        __('Title text', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'title'),
        __('Slogan text', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'slogan'), ),

    'vz_text_footer' => array(
        __('Footer Texting', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Show footer copyright', 'vz_terms') => array( 
            'type' => 'checkbox', 
            'name' => 'copyright_disabled',
            'default' => 'enabled',
            'description' => __('Showing footer copyright is a web standard.', 'vz_terms')),
        __('Left footer text &copy;', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'left'),
        __('Right footer text', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'right'), ),

    'vz_text_mtranslate' => array(
        __('Guide to trasnlation', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('How to translate po mo files', 'vz_terms') => array( 
            'type' => 'mtranslation' ), ),



    /*********************
    * Styling 
    *********************/
    'vz_styling_presets' => array(
        __('Select a preset which represents your branding', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Choose a preset', 'vz_terms') => array( 
            'type' => 'presets',
            'presets' => array('red','green','navy','orange','purple','teal'),
            'name' => 'actual'),),

    'vz_styling_sizing' => array(
        __('Headings font size in pixels', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('H1', 'vz_terms') => array( 
            'type' => 'slider',
            'name' => 'h1',
            'default_val' => '18'),
        __('H2', 'vz_terms') => array( 
            'type' => 'slider',
            'name' => 'h2',
            'default_val' => '16'),
        __('H3', 'vz_terms') => array( 
            'type' => 'slider',
            'name' => 'h3',
            'default_val' => '14'),
        __('H4', 'vz_terms') => array( 
            'type' => 'slider',
            'name' => 'h4',
            'default_val' => '12'),
        __('H5', 'vz_terms') => array( 
            'type' => 'slider',
            'name' => 'h5',
            'default_val' => '11'),
        __('H6', 'vz_terms') => array( 
            'type' => 'slider',
            'name' => 'h6',
            'default_val' => '10'),
        __('Content font size in pixels', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Default', 'vz_terms') => array( 
            'type' => 'slider',
            'name' => 'font',
            'default_val' => '12'),
        __('Link', 'vz_terms') => array( 
            'type' => 'slider',
            'name' => 'link',
            'default_val' => '12'),
        __('Date', 'vz_terms') => array( 
            'type' => 'slider',
            'name' => 'date',
            'default_val' => '11'), ),

    'vz_styling_main' => array(
        __('Advanced color managing', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Advanced management', 'vz_terms') => array( 
            'type' => 'checkbox', 
            'name' => 'advanced_enabled',
            'default' => 'disabled',
            'description' => __('If you want to manage detailed parts colors of theme you can enable this option.', 'vz_terms') ), ),

    'vz_styling_header' => array(
        __('Manage header colors', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Header background', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'bg',
            'init' => 'hex'),
        __('Header separator', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'sp',
            'init' => 'hex'),
        __('Font', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'font',
            'init' => 'hex'),
        __('Slogan font', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'slogan',
            'init' => 'hex'),
        __('Link', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'link',
            'init' => 'hex'),
        __('Link hover', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'link_hover',
            'init' => 'hex'),
        __('Social icon background', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'social_bg',
            'init' => 'hex'),
        __('Social icon hover background', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'social_hover_bg',
            'init' => 'hex'),
        __('Blank-4', 'vz_terms') => array( 
            'type' => 'tall_blank'),

        __('Manage main navigation colors', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Link ', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'main_nav_link',
            'init' => 'hex'),
        __('Link hover ', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'main_nav_link_hover',
            'init' => 'hex'),
        __('Link current', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'main_nav_link_active',
            'init' => 'hex'),
        __('Border', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'main_nav_border',
            'init' => 'hex'),
        __('Background', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'main_nav_bg',
            'init' => 'hex'),
        __('Hover background', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'main_nav_hover_bg',
            'init' => 'hex'),),

    'vz_styling_sidebar' => array(
        __('Manage default widget colors', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Background', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'widget_bg',
            'init' => 'hex'),
        __('Title', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'widget_h1',
            'init' => 'hex'),
        __('Font', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'widget_font',
            'init' => 'hex'),
        __('Link', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'widget_link',
            'init' => 'hex'),
        __('Blank-1', 'vz_terms') => array( 
            'type' => 'short_blank'),
        __('Blank-2', 'vz_terms') => array( 
            'type' => 'short_blank'),
        __('Manage why us widget colors', 'vz_terms') => array( 
            'type' => 'heading' ),
        __(' Background', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'widget_why_bg',
            'init' => 'hex'),
        __(' Title', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'widget_why_h1',
            'init' => 'hex'),
        __(' Font', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'widget_why_font',
            'init' => 'hex'),
        __(' Link', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'widget_why_link',
            'init' => 'hex'),
        __('Dotted Border', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'widget_why_dborder',
            'init' => 'hex'),
        __('Blank-3', 'vz_terms') => array( 
            'type' => 'short_blank'),
        __('Manage path widget colors', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('  Background', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'widget_path_bg',
            'init' => 'hex'),
        __('  Link', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'widget_path_link',
            'init' => 'hex'),
        __('  Link hover', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'widget_path_link_hover',
            'init' => 'hex'),
        __('Manage subscribe widget colors', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('   Background', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'widget_sub_bg',
            'init' => 'hex'),
        __('   Title', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'widget_sub_h1',
            'init' => 'hex'),
        __('   Font', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'widget_sub_font',
            'init' => 'hex'),
        __('   Link', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'widget_sub_link',
            'init' => 'hex'), ),

    'vz_styling_content' => array(
        __('Manage font colors', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Default', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'font',
            'init' => 'hex'),
        __('Link', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'link',
            'init' => 'hex'),
        __('Link hover', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'link_hover',
            'init' => 'hex'),
        __('Title', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'h1',
            'init' => 'hex'),
        __('Blank-1', 'vz_terms') => array( 
            'type' => 'short_blank'),
        __('Blank-2', 'vz_terms') => array( 
            'type' => 'short_blank'),
        __('Manage tables color', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Title background', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'table_h_bg',
            'init' => 'hex'),
        __('Title font', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'table_h_font',
            'init' => 'hex'),
        __('Default font', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'table_font',
            'init' => 'hex'),
        __('Manage lists color', 'vz_terms') => array( 
            'type' => 'heading' ),
        __(' Default font', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'list_font',
            'init' => 'hex'),
        __(' Link font', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'list_link',
            'init' => 'hex'),
        __('Blank-3', 'vz_terms') => array( 
            'type' => 'short_blank'),
        __('Manage tabs color', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Titles background', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'tab_h_bg',
            'init' => 'hex'),
        __('Titles font', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'tab_h_font',
            'init' => 'hex'),
        __('Active title font', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'tab_ah_font',
            'init' => 'hex'),
        __('Manage accordion color', 'vz_terms') => array( 
            'type' => 'heading' ),
        __(' Titles background', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'ac_h_bg',
            'init' => 'hex'),
        __(' Titles font', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'ac_h_font',
            'init' => 'hex'),
        __(' Active title font', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'ac_ah_font',
            'init' => 'hex'),

        ),

    'vz_styling_buttons' => array(
        __('Manage button colors: main button', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Font', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'main_button_font',
            'class' => 'button_sample',
            'init' => 'hex'),
        __('Background', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'main_button_bg',
            'class' => 'button_sample',
            'init' => 'hex'),
        __('Background hover', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'main_button_bghover',
            'class' => 'button_sample',
            'init' => 'hex'),
        __('Border', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'main_button_border',
            'class' => 'button_sample',
            'init' => 'hex'),
        __('Blank-3', 'vz_terms') => array( 
            'type' => 'short_blank'),
        __('Main sample', 'vz_terms') => array( 
            'type' => 'button',
            'class' => 'main'),

        __('Manage button colors: second button', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Font ', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'second_button_font',
            'class' => 'button_sample',
            'init' => 'hex'),
        __(' Background', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'second_button_bg',
            'class' => 'button_sample',
            'init' => 'hex'),
        __('Background hover ', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'second_button_bghover',
            'class' => 'button_sample',
            'init' => 'hex'),
        __('Border ', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'second_button_border',
            'class' => 'button_sample',
            'init' => 'hex'),
        __('Blank-5', 'vz_terms') => array( 
            'type' => 'short_blank'),
        __('Second sample', 'vz_terms') => array( 
            'type' => 'button',
            'class' => 'second'),

        __('Manage button colors: third button', 'vz_terms') => array( 
            'type' => 'heading' ),
        __(' Font', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'third_button_font',
            'class' => 'button_sample',
            'init' => 'hex'),
        __('  Background', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'third_button_bg',
            'class' => 'button_sample',
            'init' => 'hex'),
        __(' Background hover', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'third_button_bghover',
            'class' => 'button_sample',
            'init' => 'hex'),
        __(' Border', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'third_button_border',
            'class' => 'button_sample',
            'init' => 'hex'),
        __('Blank-6', 'vz_terms') => array( 
            'type' => 'short_blank'),
        __('Third sample', 'vz_terms') => array( 
            'type' => 'button',
            'class' => 'third'),

        __('Manage main pagination button colors', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('  Font', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'pag_main_font',
            'init' => 'hex'),
        __('   Background', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'pag_main_bg',
            'init' => 'hex'),
        __('  Border', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'pag_main_border',
            'init' => 'hex'),
        __('   Font hover', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'pag_main_font_h',
            'init' => 'hex'),
        __('    Background hover', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'pag_main_bg_h',
            'init' => 'hex'),
        __('   Border hover', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'pag_main_border_h',
            'init' => 'hex'), ),

    'vz_styling_footer' => array(
        __('Manage footer colors', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Top border', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'top_border',
            'init' => 'hex'),
        __('Background', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'bg',
            'init' => 'hex'),
        __('Copyright font', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'copyright',
            'init' => 'hex'),
        __('Manage footer widget area colors', 'vz_terms') => array( 
            'type' => 'heading' ),
        __(' Background', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'widgets_bg',
            'init' => 'hex'),
        __('Bottom border', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'widgets_bottom_border',
            'init' => 'hex'),
        __('Blank-1', 'vz_terms') => array( 
            'type' => 'short_blank'),

        __('Manage footer navigation colors', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Main link', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'nav_parent',
            'init' => 'hex'),
        __('Sub links', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'nav_children',
            'init' => 'hex'),
        __('Sub links hover', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'nav_children_hover',
            'init' => 'hex'),
        __(' Bottom border', 'vz_terms') => array( 
            'type' => 'colorpicker',
            'size' => 'short',
            'name' => 'nav_bottom_border',
            'init' => 'hex'), ),



    /*********************
    * Theme plugins
    *********************/
    'vz_plugins_forms' => array(
        __('Actual forms', 'vz_terms') => array( 
            'type' => 'heading',
            'toggle' => TRUE ),
        __('The forms', 'vz_terms') => array( 
            'type' => 'forms' ), ),

    'vz_plugins_newsletter' => array(
        __('Actual subscribers', 'vz_terms') => array( 
            'type' => 'heading',
            'toggle' => TRUE ),
        __('The subscribers', 'vz_terms') => array( 
            'type' => 'subscribers' ),

        __('Information', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Email from (Write your email you want to appear for subscribers ex. info@yoursite.com)', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'email',
            'init' => 'email'),
        __('Subject', 'vz_terms') => array( 
            'type' => 'input',
            'name' => 'subject',
            'init' => 'text'),
        __('Message', 'vz_terms') => array( 
            'type' => 'textarea',
            'name' => 'message'), ),

    'vz_plugins_extra' => array(      
        __('Extra theme plugins', 'vz_terms') => array( 
            'type' => 'heading' ),
        __('Enable blogging', 'vz_terms') => array( 
            'type' => 'checkbox', 
            'name' => 'blogging',
            'description' => __('Let users post and subscribe to each other.', 'vz_terms') ),
        __('Enable calendar', 'vz_terms') => array( 
            'type' => 'checkbox', 
            'name' => 'calendar',
            'description' => __('Enable calendar to let users manage their time.', 'vz_terms') ),
        __('Enable file sharing', 'vz_terms') => array( 
            'type' => 'checkbox', 
            'name' => 'file_sharing',
            'description' => __('Enable users to share their files.', 'vz_terms') ), 
        __('Extra part', 'vz_terms') => array( 'type' => 'extra_part' ), ),

);


# In case user chooses basic color editing
if( !get_option('vz_styling_main_advanced_enabled') ) :

    $vz_theme_options_pages['vz_styling_main'][__('Manage main colors','vz_terms')] = array( 'type' => 'heading' );
    $vz_theme_options_pages['vz_styling_main'][__('Main color','vz_terms')]         = array( 'type' => 'colorpicker', 'size' => 'short', 'name' => 'main', 'init' => 'hex' );
    $vz_theme_options_pages['vz_styling_main'][__('Gold color','vz_terms')]         = array( 'type' => 'colorpicker', 'size' => 'short', 'name' => 'gold', 'init' => 'hex' );
    $vz_theme_options_pages['vz_styling_main'][__('Font color','vz_terms')]         = array( 'type' => 'colorpicker', 'size' => 'short', 'name' => 'font', 'init' => 'hex' );
    $vz_theme_options_pages['vz_styling_main'][__('Link color','vz_terms')]         = array( 'type' => 'colorpicker', 'size' => 'short', 'name' => 'link', 'init' => 'hex' );
    $vz_theme_options_pages['vz_styling_main'][__('Title color','vz_terms')]        = array( 'type' => 'colorpicker', 'size' => 'short', 'name' => 'title', 'init' => 'hex' );

endif;